#!/bin/bash

bash /usr/local/taiga/configure

cd /usr/local/taiga/taiga-back/

python manage.py collectstatic --noinput

#echo "Waiting for Postgresql to be available..."
#while ! nc -z $POSTGRES_PORT_5432_TCP_ADDR 5432; do
#  sleep 1
#done

pip install --upgrade -r requirements.txt
python manage.py migrate --noinput
python manage.py migrate taiga_contrib_slack
python manage.py collectstatic --noinput
circusctl reload taiga
chown -R taiga /usr/local/taiga/media /usr/local/taiga/static /usr/local/taiga/logs
#provisório até ver o problema do circus
python manage.py runserver
#/usr/local/bin/circusd /usr/local/taiga/circus.ini
